from datetime import datetime
current_time=datetime.now()
print(current_time)
format2=current_time.strftime("%Y-%m-%d %H:%M:%S")
print(format2)
a=current_time.strftime("%m/%d/%Y")
print(a)
b=current_time.strftime("%A,%b,%d,%Y")
print(b)
c=current_time.strftime("%A,%b,%d,%Y %I:%M:%S %p")
print(c)
d=current_time.strftime("%a-%b-%d %H:%M:%S %Z %Y")
print(d)
e=current_time.strftime("%a-%b-%d %H:%M:%S %Z %Y")
print(e)
f=current_time.strftime(current_time.isoformat())
print(f)
g=current_time.strftime("%d")
print(g)
print(current_time)
h=current_time.strftime("%B")
print(h)
i=current_time.strftime("%Y")
print(i)